task13.4
psadovski/kodilla-course pull request #37
Opened 2018-08-15 08:28 UTC by psadovski

2018-08-15 18:05 UTC, mps4dev requested changes

2018-08-15 18:05 UTC, mps4dev commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/manytomany/Company.java
> +    @Column(name = "COMPANY_NAME")
po co tak komplikowac nazwy? Czy nie wystarczy nazwac kolumne „name”?

2018-08-15 18:05 UTC, mps4dev commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/manytomany/Company.java
> +    @NotNull
nie moglo byc „id”?

2018-08-15 18:05 UTC, mps4dev commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/manytomany/Employee.java
> +    @Column(name = "EMPLOYEE_ID", unique = true)
jw

2018-08-15 18:05 UTC, mps4dev commented on kodilla-hibernate/src/test/java/com/kodilla/hibernate/manytomany/dao/CompanyDaoTestSuite.java
> +        //Then
czy to wystarczajacy warunek? Jesli znajdzie przez pomylke innego, to u ciebie test przejdzie

2018-08-15 18:05 UTC, mps4dev commented on kodilla-hibernate/src/test/java/com/kodilla/hibernate/manytomany/dao/CompanyDaoTestSuite.java
> +        //Then
podobnie

2018-08-23 19:11 UTC, xmarcinsx requested changes
:-1:

2018-08-23 19:11 UTC, xmarcinsx commented on kodilla-hibernate/src/test/java/com/kodilla/hibernate/manytomany/dao/CompanyDaoTestSuite.java
> +        companyList.forEach(company -> Assert.assertEquals("Software Machine", company.getName()));
Assert.assertEquals("Sof", company.getName().substring(0,3));

2018-08-29 15:44 UTC, mps4dev approved these changes
👍

2018-08-30 16:36 UTC, merged